[package]
name = "fit2walking"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4" }
clap = { version = "3.0.0-rc.7", features = ["derive"] }
fitparser = { version = "0.4" }
geo = { version = "0.18" }
serde_json = { version = "1.0" }
