[package]
name = "fit2walking"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4" }
clap = { version = "4.4", features = ["derive"] }
fitparser = { version = "0.6" }
geo = { version = "0.26" }
serde_json = { version = "1.0" }
